-- --crIando um banco de dados(database),

-- CREATE TABLE IF NOT EXISTS PRODUTO(
-- ID int PRIMARY KEY,
-- COD VARCHAR(4) NOT NULL UNIQUE,

-- NOME VARCHAR(100) NOT NULL,
-- PRECO REAL CHECK(PRECO>0)



-- );
-- --\dt;
-- \d PRODUTO;

-- --DELETANDO UMA BASE DE DADOS
-- --DROP DATABASE AULA0312,
-- DROP TABLE PRODUTO;
-- \dt



-- criando uma tabela
-- PROFESSOR(id, nome, cof)
--turma 9id, numero, duracao_dias)


CREATE TABLE PROFESSOR (
id int PRIMARY KEY,
COD VARCHAR(100),
NOME VARCHAR(100) NOT NULL,
CPF CHAR(11) NOT NULL UNIQUE

);
CREATE TABLE TURMA(
id int ,
NUMERO_TURMA int not null unique,
DURACAO_DIAS VARCHAR(4),

PRIMARY KEY(id, numero_turma)


);

\dt
\d TURMA

CREATE TABLE IF NOT EXISTS FORNECEDOR(
ID INT PRIMARY KEY,
NOME_FORNECEDOR VARCHAR (100) NOT NULL,
CIDADE VARCHAR(100)


);

CREATE TABLE PECA(
ID INT PRIMARY KEY,

NOME_PECA VARCHAR(100) NOT NULL,
DESCRICAO TEXT




);

CREATE TABLE VENDA (
ID INT PRIMARY KEY,
ID_FORNECEDOR INT,
ID_PECA INT,

NOME_VENDA VARCHAR(100) NOT NULL,
DATA date,
QUANTIDADE INT,


 CONSTRAINT fk_FORNECEDOR FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDOR(ID),
 CONSTRAINT fk_PECA FOREIGN KEY(ID_PECA) REFERENCES PECA(ID)







);


-- \dt
-- \d FORNECEDOR
-- \d PECA
-- \d venda


ALTER TABLE FORNECEDOR ADD TELEFONE CHAR (10);
\d FORNECEDOR
ALTER TABLE PECA ADD PRECO REAL;
\d PECA
ALTER TABLE FORNECEDOR DROP CIDADE ;
 \d FORNECEDOR